version: '3'

services:

  db:
    image: mariadb
    volumes: 
        - './data:/var/lib/mysql'
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: bonfire

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080

  api:
    build: ./api/.
    ports:
        - 3000:3000